pool:
  vmImage: 'ubuntu-latest'
variables:
  NodeVersion: 12
  FORCE_COLOR: 1
steps:
  - checkout: self
    persistCredentials: true
  - template: templates/build.yaml
  - template: templates/publish.yaml
    parameters:
      VersionPolicyName: noRush
  - template: templates/record-published-versions.yaml
